import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 199.99,
    originalPrice: 299.99,
    image: "/wireless-headphones.png",
    category: "Electronics",
    subcategory: "Audio",
    rating: 4.8,
    reviews: 342,
    inStock: true,
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
    images: ["/wireless-headphones-front.png", "/wireless-headphones-side.png", "/wireless-headphones-detail.png"],
  },
  {
    id: "2",
    name: "Classic Cotton T-Shirt",
    price: 29.99,
    originalPrice: 49.99,
    image: "/cotton-t-shirt.jpg",
    category: "Fashion",
    subcategory: "Men",
    rating: 4.5,
    reviews: 218,
    inStock: true,
    description: "Comfortable and breathable cotton t-shirt perfect for everyday wear.",
    images: ["/cotton-t-shirt-front.jpg", "/cotton-t-shirt-back.jpg"],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray"],
  },
  {
    id: "3",
    name: "Stainless Steel Water Bottle",
    price: 34.99,
    image: "/stainless-steel-bottle.png",
    category: "Accessories",
    subcategory: "Sports",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    description: "Insulated stainless steel water bottle keeps drinks cold for 24 hours.",
    images: ["/water-bottle-front.jpg", "/water-bottle-side.jpg"],
    colors: ["Silver", "Black", "Blue"],
  },
  {
    id: "4",
    name: "Slim Fit Denim Jeans",
    price: 79.99,
    originalPrice: 129.99,
    image: "/slim-fit-denim-jeans.jpg",
    category: "Fashion",
    subcategory: "Men",
    rating: 4.6,
    reviews: 289,
    inStock: true,
    description: "Perfect fitting slim jeans with premium denim quality.",
    images: ["/front-jeans.png", "/jeans-side.jpg"],
    size: ["28", "30", "32", "34", "36", "38"],
    colors: ["Dark Blue", "Light Blue", "Black"],
  },
  {
    id: "5",
    name: "Minimalist Watch",
    price: 149.99,
    image: "/minimalist-watch.png",
    category: "Accessories",
    subcategory: "Watches",
    rating: 4.9,
    reviews: 412,
    inStock: true,
    description: "Elegant minimalist watch with Japanese movement.",
    images: ["/watch-front.jpg", "/watch-side.png"],
  },
  {
    id: "6",
    name: "Yoga Mat Pro",
    price: 44.99,
    originalPrice: 69.99,
    image: "/rolled-yoga-mat.png",
    category: "Sports",
    subcategory: "Fitness",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    description: "High-grip yoga mat with alignment markers.",
    images: ["/rolled-yoga-mat.png", "/rolled-yoga-mat.png"],
    colors: ["Purple", "Black", "Teal"],
  },
]

export const categories = [
  { id: "electronics", name: "Electronics", icon: "📱" },
  { id: "fashion", name: "Fashion", icon: "👕" },
  { id: "accessories", name: "Accessories", icon: "⌚" },
  { id: "sports", name: "Sports", icon: "⚽" },
]
